name: Release

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Windows
        run: npm run build:win

      - name: Rename Windows artifact
        run: mv dist/koclauncher-setup.exe Knockoutcitylauncher-Setup.exe

      - name: Upload Windows binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Knockoutcitylauncher-Setup.exe
          asset_name: Knockoutcitylauncher-Setup.exe
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload latest.yml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/latest.yml
          asset_name: latest.yml
          tag: ${{ github.ref }}
          overwrite: true

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install system dependencies for Linux targets
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder fakeroot libarchive-tools zip
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build Linux
        run: npm run build:linux

      - name: Zip Linux Unpacked
        run: cd dist && zip -r Knockoutcitylauncher.zip linux-unpacked/

      - name: Upload AppImage to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/koclauncher.AppImage
          asset_name: Knockoutcitylauncher.AppImage
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload flatpak to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/koclauncher.flatpak
          asset_name: Knockoutcitylauncher.flatpak
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload pacman to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/koclauncher.pacman
          asset_name: Knockoutcitylauncher.pacman
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload deb to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/koclauncher.deb
          asset_name: Knockoutcitylauncher.deb
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/koclauncher.zip
          asset_name: Knockoutcitylauncher.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload latest-linux.yml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/latest-linux.yml
          asset_name: latest-linux.yml
          tag: ${{ github.ref }}
          overwrite: true